### ISSUE TITLE
Prepare test data sets

### ISSUE THREAD

**Issue by ramilyayus** [ramilyayus/WeRec-specs#16]
We need basic data for testing like: keyword + array of YT channels.
Topics like news, food, sport, health, kid stuff, etc.

**Comment by aalexsm** [comment]
Pop-science:
https://www.youtube.com/user/toplesofficial

Humor:
https://www.youtube.com/c/%D0%A8%D0%90%D0%A1%D0%A2%D0%A3%D0%9D
https://www.youtube.com/c/standupclubru

Cartoons:
https://www.youtube.com/channel/UCbCmjCuTUZos6Inko4u57UQ
https://www.youtube.com/c/smeshariki
https://www.youtube.com/c/Soyuzmultfilm

Games:
https://www.youtube.com/user/PewDiePie
https://www.youtube.com/c/jacksepticeye
https://www.youtube.com/c/kuplinovplay

Books:
https://www.youtube.com/c/AnthonyUly

Music:
https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
https://www.youtube.com/c/MTV
https://www.youtube.com/user/bbcradio1

Politics:
https://www.youtube.com/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ
https://www.youtube.com/c/NavalnyLiveChannel

Interviews:
https://www.youtube.com/channel/UCp2J7GRxQ36QLqW4ReLLt5g
https://www.youtube.com/c/vdud

**Comment by aalexsm** [comment]
Food:
https://www.youtube.com/c/IVLEVCHEF
https://www.youtube.com/c/%D0%9F%D1%80%D0%BE%D0%A1%D1%82%D0%BE%D0%BA%D1%83%D1%85%D0%BD%D1%8F%D0%A1%D0%A2%D0%A1
https://www.youtube.com/c/oblomoffstuff

Sport:
https://www.youtube.com/c/ChloeTing
https://www.youtube.com/channel/UC5Y4crUlvKIomg7ArCj3G8Q
